name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Deployment
      uses: appleboy/ssh-action@master
      with:
        host: 34.128.85.72
        username: habib
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd /var/www/laravel-ci
          ./deployer.sh


